version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
      - image: redis
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install libgtk-3-0 libnss3 libxss1 libgconf-2-4 libasound2
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn greenkeeper-lockfile-update
      - run: yarn test-all
      - run: yarn greenkeeper-lockfile-upload
